#!/usr/bin/env bash
# Root-side setup of the private galaxy replica's host guards and web front on battlecode-dev (Debian 12).
# Every step is idempotent. The driver runs this through deploy.sh; see docs/replica/DEPLOY.md.
#
#   sudo vm-setup.sh all              install + user + egress + caddy + services (Caddy starts once a password and a
#                                     host exist)
#   sudo vm-setup.sh install          copy these scripts to /usr/local/lib/bc23-replica (root-owned; systemd runs them)
#   sudo vm-setup.sh user             user bcreplica (no credentials, locked, nologin), REPLICA_HOME, operator group
#   sudo vm-setup.sh egress           nftables table: bcreplica may use loopback only; metadata server dropped
#   sudo vm-setup.sh caddy            Caddy static binary (checksum-verified), user caddy, systemd units
#   sudo vm-setup.sh password <file   bcrypt the password on stdin (one line) into the Caddyfile and reload
#   sudo vm-setup.sh render [--boot]  rebuild the Caddyfile from /etc/bc23-replica/{hostname,owner.bcrypt}, reload
#   sudo vm-setup.sh services         replica units: api + worker (enabled, started), autoscrim timer (installed
#                                     DISABLED), env file /etc/bc23-replica/replica.env, CLI wrapper bc23-replica
#   sudo vm-setup.sh status
#   sudo vm-setup.sh teardown-web     remove Caddy (binary, units, certs, logs, user caddy); keep the lockdown
#   sudo vm-setup.sh teardown-services             stop and remove the replica units and the CLI wrapper
#   sudo vm-setup.sh teardown-all [--purge-data]   also remove the lockdown and user bcreplica (data kept unless asked)
#   vm-setup.sh print-nft UID "PORTS" | print-caddyfile HOST HASH [1] | print-units | print-env | print-cli
#             | print-dbus-policy | print-nft-dropin   (no root; used by test/replica/test_deploy.py)
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=config.sh
source "$HERE/config.sh"
DOC=/home/$OPERATOR_USER/projects/vibe/2023/docs/replica/DEPLOY.md

die () { echo "vm-setup: $*" >&2; exit 1; }
as_caddy () { (cd /var/lib/caddy && runuser -u caddy -- env HOME=/var/lib/caddy "$CADDY_BIN" "$@"); }
say () { echo "== $*"; }

HOST_RE='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$'
HASH_RE='^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$'
PORTS_RE='^[0-9]{1,5}( [0-9]{1,5})*$'

# ---------------------------------------------------------------------------------------------------------- renderers
print_nft () {  # $1 uid, $2 space-separated loopback ports
  local uid="$1" ports="$2"
  [[ $uid =~ ^[0-9]+$ ]] || die "bad uid '$uid'"
  [[ $ports =~ $PORTS_RE ]] || die "bad port list '$ports'"
  cat <<EOF
#!/usr/sbin/nft -f
# Egress lockdown for uid $uid ($REPLICA_USER), the private galaxy replica (bc23).
# Generated by $LIB_DIR/vm-setup.sh; loaded at boot by $UNIT_EGRESS. Touches only this table (no flush ruleset).
# Doc: $DOC
table inet $NFT_TABLE
delete table inet $NFT_TABLE
table inet $NFT_TABLE {
	chain output {
		type filter hook output priority filter - 10; policy accept;
		meta skuid $uid jump replica comment "$REPLICA_USER"
	}
	chain replica {
		ip daddr 169.254.169.254 counter drop comment "GCE metadata server: no service-account token, no metadata DNS"
		ip6 daddr fd20:ce::254 counter drop comment "GCE metadata server (IPv6)"
		oifname != "lo" limit rate 6/minute burst 5 packets log prefix "bc23-replica-egress-drop: " level info
		oifname != "lo" counter drop comment "no off-host egress"
		ct state established,related accept comment "replies on loopback (web server to Caddy)"
		tcp dport { ${ports// /, } } accept comment "replica web server"
		counter drop comment "no other loopback service (DNS stub, MTA, Caddy admin)"
	}
}
EOF
}

print_nft_dropin () {  # drop-in for nftables.service + the file it loads; split on '### <path>' lines
  cat <<EOF
### $NFT_DROPIN
# bc23 replica: /etc/nftables.conf begins with "flush ruleset", which would delete table inet $NFT_TABLE whenever
# nftables.service starts or reloads. Load it together with the egress table in ONE nft transaction (atomic).
# Generated by $LIB_DIR/vm-setup.sh egress. Doc: $DOC
[Service]
ExecStart=
ExecStart=/usr/sbin/nft -f $NFT_COMBINED
ExecReload=
ExecReload=/usr/sbin/nft -f $NFT_COMBINED
### $NFT_COMBINED
#!/usr/sbin/nft -f
# Loaded by nftables.service (drop-in $NFT_DROPIN): the system ruleset, then the replica's egress table.
include "/etc/nftables.conf"
include "$ETC_DIR/egress.nft"
EOF
}

print_dbus_policy () {  # D-Bus is a unix socket, which nftables does not see: close the services that do network work
  cat <<EOF
<?xml version="1.0"?>
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<!-- bc23 replica: user $REPLICA_USER may not ask systemd-resolved to resolve names (a DNS path around the nftables
     egress table), nor networkd or timesyncd to do anything. Generated by $LIB_DIR/vm-setup.sh egress.
     Doc: $DOC -->
<busconfig>
  <policy user="$REPLICA_USER">
    <deny send_destination="org.freedesktop.resolve1"/>
    <deny send_destination="org.freedesktop.network1"/>
    <deny send_destination="org.freedesktop.timesync1"/>
  </policy>
</busconfig>
EOF
}

read_only_block () {  # basic_auth runs before respond (Caddy's directive order): 401 first, then 405 for writes
  [ "${PUBLIC_READ_ONLY:-1}" = 1 ] || return 0
  printf '\t%s\n' '@write not method GET HEAD' \
    'respond @write "Read-only web front: run replica commands on the VM (docs/replica/DEPLOY.md)." 405'
}

print_caddyfile () {  # $1 host, $2 bcrypt hash, $3 = 1: also the galaxy replica's site (galaxy.$1)
  local host="$1" hash="$2" galaxy="${3:-0}"
  [[ $host =~ $HOST_RE ]] || die "bad host name '$host'"
  [[ $hash =~ $HASH_RE ]] || die "bad bcrypt hash"
  cat <<EOF
# Generated by $LIB_DIR/vm-setup.sh render. Do not edit by hand: the host name comes from $ETC_DIR/hostname
# (refresh-hostname.sh) and the hash from $ETC_DIR/owner.bcrypt (set-password.sh). Doc: $DOC
{
	admin unix//run/caddy/admin.sock
	servers {
		protocols h1 h2
	}
}

$host {
	log {
		output file /var/log/caddy/access.log {
			roll_size 10MiB
			roll_keep 5
		}
	}
	header {
		-Server
		Strict-Transport-Security "max-age=31536000"
		X-Content-Type-Options nosniff
		X-Frame-Options SAMEORIGIN
		Referrer-Policy no-referrer
	}
	basic_auth {
		$OWNER_LOGIN $hash
	}
$(read_only_block)
	encode zstd gzip
	reverse_proxy 127.0.0.1:$REPLICA_PORT {
		header_up -Authorization
	}
}
EOF
  if [ "$galaxy" = 1 ]; then
    [ -x "${GALAXY_SETUP:-}" ] || die "galaxy site requested but ${GALAXY_SETUP:-<unset>} is missing"
    "$GALAXY_SETUP" print-site "$host" "$hash" || die "galaxy-setup.sh print-site failed"
  fi
}

# ------------------------------------------------------------------------------------------ the replica's own units
print_env () {
  cat <<EOF
# Environment of the bc23 replica services ($UNIT_API, $UNIT_WORKER, $UNIT_AUTOSCRIM) and of $REPLICA_CLI.
# Written once by $LIB_DIR/vm-setup.sh services; later runs keep your edits. Restart the units after a change.
REPLICA_HOME=$REPLICA_HOME
REPLICA_REPO=$REPLICA_REPO
JAVA_HOME=$REPLICA_JAVA_HOME
BENCH_ROOT=$REPLICA_BENCH_ROOT
REPLICA_SLOTS=$REPLICA_SLOTS
REPLICA_AUTOSCRIM_MAX_BACKLOG=0
REPLICA_TZ=America/Los_Angeles
PYTHONDONTWRITEBYTECODE=1
PYTHONUNBUFFERED=1
EOF
}

service_common () {  # the contract of DEPLOY.md section 4, plus filesystem hardening
  cat <<EOF
User=$REPLICA_USER
Group=$REPLICA_GROUP
Slice=$SLICE
UMask=0027
EnvironmentFile=$REPLICA_ENV
WorkingDirectory=$REPLICA_HOME
# Unix sockets bypass nftables: no varlink or D-Bus to systemd-resolved (DNS lookups made on our behalf).
InaccessiblePaths=-/run/systemd/resolve -/run/dbus/system_bus_socket
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=$REPLICA_HOME
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
LockPersonality=yes
EOF
}

print_units () {  # all four units, each after a '### <name>' line (services_step splits them)
  local head="Documentation=file://$DOC
Requires=$UNIT_EGRESS
After=$UNIT_EGRESS network.target"
  cat <<EOF
### $UNIT_API
[Unit]
Description=bc23 replica: web pages, replay viewer and JSON API on 127.0.0.1:$REPLICA_PORT
$head

[Service]
Type=simple
$(service_common)
# The API shares the host network namespace (Caddy connects to it), so it relies on the nftables table: refuse to
# start when the table is gone (e.g. flushed by hand) although $UNIT_EGRESS still reads active. (The worker and
# autoscrim units cannot run this check: '+' commands still run in their private network namespace.)
ExecStartPre=+/bin/sh -c 'exec /usr/sbin/nft list table inet $NFT_TABLE >/dev/null'
ExecStart=/usr/bin/python3 \${REPLICA_REPO}/tools/replica.py serve --host 127.0.0.1 --port $REPLICA_PORT
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
### $UNIT_WORKER
[Unit]
Description=bc23 replica: match worker (runs queued matches with the pinned engine)
$head $UNIT_API

[Service]
Type=simple
$(service_common)
# The worker and its engines need no network at all: an own network namespace with only a loopback device (no route
# out, no listener reachable from the VPC even without -Dbc.server.websocket=false, no abstract unix sockets).
PrivateNetwork=yes
ExecStart=/usr/bin/python3 \${REPLICA_REPO}/tools/replica.py run-worker --slots \${REPLICA_SLOTS}
# SIGTERM goes to the worker only: it stops its engines and requeues their matches as interrupted (no failure counted)
KillMode=mixed
TimeoutStopSec=120
Restart=on-failure
RestartSec=30s

[Install]
WantedBy=multi-user.target
### $UNIT_AUTOSCRIM
[Unit]
Description=bc23 replica: one autoscrim round (4 ranked best-of-3 matches per team) unless matches are still queued
$head

[Service]
Type=oneshot
$(service_common)
PrivateNetwork=yes
# Skip the round while more than REPLICA_AUTOSCRIM_MAX_BACKLOG matches (default 0) still wait in the queue.
ExecCondition=/usr/bin/python3 -c "import os, sqlite3, sys; f = os.environ['REPLICA_HOME'] + '/replica.db'; n = sqlite3.connect('file:' + f + '?mode=ro', uri=True).execute('SELECT COUNT(*) FROM match WHERE status IN (?, ?, ?)', ('NEW', 'QUE', 'TRY')).fetchone()[0]; cap = int(os.environ.get('REPLICA_AUTOSCRIM_MAX_BACKLOG') or 0); print(n, 'matches queued, backlog cap', cap); sys.exit(0 if n <= cap else 1)"
ExecStart=/usr/bin/python3 \${REPLICA_REPO}/tools/replica.py autoscrim
### $TIMER_AUTOSCRIM
[Unit]
Description=bc23 replica: autoscrim every 4 hours
Documentation=file://$DOC

[Timer]
OnCalendar=$AUTOSCRIM_CALENDAR
AccuracySec=1min
Persistent=false
Unit=$UNIT_AUTOSCRIM

[Install]
WantedBy=timers.target
EOF
}

print_cli () {
  cat <<EOF
#!/usr/bin/env bash
# The galaxy-lite CLI (tools/replica.py) as user $REPLICA_USER with the services' environment ($REPLICA_ENV).
# Installed by $LIB_DIR/vm-setup.sh services. Examples: bc23-replica status | ratings | autoscrim | request A B --ranked
# Writes need this wrapper (the DB belongs to $REPLICA_USER); reads also work as any member of group $REPLICA_GROUP.
set -euo pipefail
ENV_FILE=$REPLICA_ENV
RUN_AS=$REPLICA_USER
NFT_TABLE=$NFT_TABLE
EOF
  cat <<'EOF'
# Commands run here (outside the services' slice and sandbox) are fenced by the nftables table alone: require it.
sudo -n /usr/sbin/nft list table inet "$NFT_TABLE" >/dev/null 2>&1 || {
  echo "bc23-replica: egress table inet $NFT_TABLE is not loaded; refusing to run (sudo systemctl restart bc23-replica-egress)" >&2
  exit 1; }
mapfile -t envs < <(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$ENV_FILE")
repo=$(sed -n 's/^REPLICA_REPO=//p' "$ENV_FILE" | tail -1)
exec sudo -u "$RUN_AS" env -i PATH=/usr/local/bin:/usr/bin:/bin HOME="/home/$RUN_AS" LANG=C.UTF-8 "${envs[@]}" \
  /usr/bin/python3 "$repo/tools/replica.py" "$@"
EOF
}

case "${1:-}" in
  print-nft) print_nft "${2:?uid}" "${3:?ports}"; exit 0 ;;
  print-caddyfile) print_caddyfile "${2:?host}" "${3:?hash}" "${4:-0}"; exit 0 ;;
  print-units) print_units; exit 0 ;;
  print-env) print_env; exit 0 ;;
  print-cli) print_cli; exit 0 ;;
  print-dbus-policy) print_dbus_policy; exit 0 ;;
  print-nft-dropin) print_nft_dropin; exit 0 ;;
esac
[ "$(id -u)" = 0 ] || die "run as root (sudo)"
[ "$(hostname -s)" = "$BC_VM" ] || [ "${BC_REPLICA_ANY_HOST:-0}" = 1 ] || die "this is $(hostname -s), not $BC_VM"

# -------------------------------------------------------------------------------------------------------------- steps
install_step () {
  say "install scripts to $LIB_DIR"
  install -d -o root -g root -m 0755 "$LIB_DIR"
  if [ "$HERE" != "$LIB_DIR" ]; then
    local f
    for f in config.sh vm-setup.sh refresh-hostname.sh; do install -o root -g root -m 0755 "$HERE/$f" "$LIB_DIR/$f"; done
  fi
}

user_step () {
  say "user $REPLICA_USER"
  getent group "$REPLICA_GROUP" >/dev/null || groupadd --system "$REPLICA_GROUP"
  if ! id -u "$REPLICA_USER" >/dev/null 2>&1; then
    useradd --system --gid "$REPLICA_GROUP" --home-dir "/home/$REPLICA_USER" --create-home --shell /usr/sbin/nologin \
      --comment "bc23 galaxy replica (no credentials, loopback-only network)" "$REPLICA_USER"
  fi
  local pwfield; pwfield=$(getent shadow "$REPLICA_USER" | cut -d: -f2)
  case "$pwfield" in '!'*|'*'*) ;; *) usermod --lock "$REPLICA_USER" ;; esac
  local extra; extra=$(id -nG "$REPLICA_USER" | tr ' ' '\n' | grep -vx "$REPLICA_GROUP" || true)
  [ -z "$extra" ] || die "$REPLICA_USER has extra groups: $extra"
  install -d -o "$REPLICA_USER" -g "$REPLICA_GROUP" -m 0750 "/home/$REPLICA_USER"
  install -d -o "$REPLICA_USER" -g "$REPLICA_GROUP" -m 2750 "$REPLICA_HOME"   # setgid: new files keep the group
  id -nG "$OPERATOR_USER" | tr ' ' '\n' | grep -qx "$REPLICA_GROUP" || usermod -aG "$REPLICA_GROUP" "$OPERATOR_USER"
  local p
  for p in .config/gcloud .boto .ssh .netrc .git-credentials .docker .aws .kube .gnupg; do
    [ ! -e "/home/$REPLICA_USER/$p" ] || die "credential-like path /home/$REPLICA_USER/$p exists; remove it"
  done
}

egress_step () {
  say "egress lockdown (nftables table inet $NFT_TABLE)"
  id -u "$REPLICA_USER" >/dev/null 2>&1 || die "run the user step first"
  if ! command -v nft >/dev/null; then
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends nftables >/dev/null \
      || { apt-get update -q >/dev/null; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends nftables >/dev/null; }
  fi
  install -d -o root -g root -m 0755 "$ETC_DIR"
  print_nft "$(id -u "$REPLICA_USER")" "$REPLICA_LO_PORTS" > "$ETC_DIR/egress.nft.new"
  chmod 0644 "$ETC_DIR/egress.nft.new"
  nft -c -f "$ETC_DIR/egress.nft.new" || die "nft rejected the generated ruleset"
  mv -f "$ETC_DIR/egress.nft.new" "$ETC_DIR/egress.nft"
  cat > "/etc/systemd/system/$UNIT_EGRESS" <<EOF
[Unit]
Description=bc23 replica: egress lockdown for user $REPLICA_USER (loopback only, metadata server dropped)
Documentation=file://$DOC
DefaultDependencies=no
Wants=network-pre.target
Before=network-pre.target shutdown.target
After=local-fs.target nftables.service
Conflicts=shutdown.target
PartOf=nftables.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/nft -f $ETC_DIR/egress.nft
ExecReload=/usr/sbin/nft -f $ETC_DIR/egress.nft
ExecStop=-/usr/sbin/nft delete table inet $NFT_TABLE

[Install]
WantedBy=sysinit.target
EOF
  # Second, independent layer for the replica's own services: a unit with Slice=$SLICE gets cgroup-BPF IP filtering.
  cat > "/etc/systemd/system/$SLICE" <<EOF
[Unit]
Description=bc23 replica services (IP traffic limited to localhost; second layer behind $UNIT_EGRESS)
Documentation=file://$DOC

[Slice]
IPAddressDeny=any
IPAddressAllow=localhost
EOF
  # nftables.service (disabled today) flushes the whole ruleset on start and reload: if anyone starts it, it must
  # load the egress table in the same transaction. (Its stop also flushes; PartOf= above then stops the replica.)
  install -d -o root -g root -m 0755 "$(dirname "$NFT_DROPIN")"
  local f
  for f in "$NFT_COMBINED" "$NFT_DROPIN"; do
    print_nft_dropin | awk -v u="### $f" '$0 == u {on = 1; next} /^### / {on = 0} on' > "$f.new"
    [ -s "$f.new" ] || die "no text for $f"
    chmod 0644 "$f.new"
  done
  nft -c -f "$NFT_COMBINED.new" || die "nft rejected $NFT_COMBINED (/etc/nftables.conf + egress.nft)"
  mv -f "$NFT_COMBINED.new" "$NFT_COMBINED"; mv -f "$NFT_DROPIN.new" "$NFT_DROPIN"
  # D-Bus: no name resolution (or network work) by systemd-resolved/networkd/timesyncd on bcreplica's behalf
  if [ -d "$(dirname "$DBUS_POLICY")" ]; then
    print_dbus_policy > "$DBUS_POLICY.new"
    # expat never fetches the DTD named in the DOCTYPE: a pure well-formedness check, no network
    python3 -c 'import sys, xml.parsers.expat as e; e.ParserCreate().Parse(open(sys.argv[1], "rb").read(), True)' \
      "$DBUS_POLICY.new" || { rm -f "$DBUS_POLICY.new"; die "generated D-Bus policy is not well-formed XML"; }
    chmod 0644 "$DBUS_POLICY.new"; mv -f "$DBUS_POLICY.new" "$DBUS_POLICY"
    if systemctl is-active --quiet dbus.service; then
      busctl call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus ReloadConfig >/dev/null \
        || die "dbus-daemon refused to reload its configuration (see journalctl -u dbus)"
    fi
  fi
  systemctl daemon-reload
  systemctl enable --quiet "$UNIT_EGRESS"
  # reload = one atomic nft transaction (delete + re-add the table): no unprotected gap, unlike a restart
  if systemctl is-active --quiet "$UNIT_EGRESS"; then systemctl reload "$UNIT_EGRESS"; else systemctl start "$UNIT_EGRESS"; fi
  nft list table inet "$NFT_TABLE" >/dev/null || die "table inet $NFT_TABLE is not loaded"
}

caddy_step () {
  say "caddy $CADDY_VERSION"
  getent group caddy >/dev/null || groupadd --system caddy
  id -u caddy >/dev/null 2>&1 || useradd --system --gid caddy --home-dir /var/lib/caddy --create-home \
    --shell /usr/sbin/nologin --comment "Caddy web server (bc23 replica front)" caddy
  install -d -o caddy -g caddy -m 0700 /var/lib/caddy
  install -d -o caddy -g caddy -m 0750 /var/log/caddy
  install -d -o root -g caddy -m 0750 /etc/caddy
  local have; have=$("$CADDY_BIN" version 2>/dev/null | awk '{print $1}' || true)
  if [ "$have" != "v$CADDY_VERSION" ]; then
    TMPD=$(mktemp -d); trap 'rm -rf "$TMPD"' EXIT; local tmp="$TMPD"
    curl --proto '=https' --tlsv1.2 -fsSL --retry 3 -m 300 -o "$tmp/$CADDY_TARBALL" "$CADDY_BASE_URL/$CADDY_TARBALL"
    curl --proto '=https' --tlsv1.2 -fsSL --retry 3 -m 60 -o "$tmp/$CADDY_SUMS" "$CADDY_BASE_URL/$CADDY_SUMS"
    local line; line=$(awk -v f="$CADDY_TARBALL" '$2 == f' "$tmp/$CADDY_SUMS")
    [ "$(printf '%s\n' "$line" | grep -c .)" = 1 ] || die "no single checksum line for $CADDY_TARBALL"
    (cd "$tmp" && printf '%s\n' "$line" | sha512sum -c --quiet -) || die "SHA-512 does not match the release checksums file"
    [ "${line%% *}" = "$CADDY_SHA512" ] || die "release checksums file differs from the pinned SHA-512"
    echo "$CADDY_SHA256  $tmp/$CADDY_TARBALL" | sha256sum -c --quiet - || die "SHA-256 does not match the pin"
    tar -xzf "$tmp/$CADDY_TARBALL" -C "$tmp" caddy
    install -o root -g root -m 0755 "$tmp/caddy" "$CADDY_BIN"
    echo "installed $("$CADDY_BIN" version | awk '{print $1}') at $CADDY_BIN (tarball sha256 $CADDY_SHA256)"
  fi
  cat > "/etc/systemd/system/$UNIT_HOSTNAME" <<EOF
[Unit]
Description=bc23 replica: point the Caddy site at this boot's external IP (<ip-with-dashes>.sslip.io)
Documentation=file://$DOC
After=network-online.target
Wants=network-online.target
Before=$UNIT_CADDY

[Service]
Type=oneshot
ExecStart=$LIB_DIR/refresh-hostname.sh --boot
TimeoutStartSec=150

[Install]
WantedBy=multi-user.target
EOF
  cat > "/etc/systemd/system/$UNIT_CADDY" <<EOF
[Unit]
Description=bc23 replica: Caddy HTTPS reverse proxy with basic auth to 127.0.0.1:$REPLICA_PORT
Documentation=file://$DOC
After=network-online.target $UNIT_HOSTNAME
Wants=network-online.target
ConditionPathExists=$CADDYFILE

[Service]
Type=notify
User=caddy
Group=caddy
ExecStart=$CADDY_BIN run --config $CADDYFILE --adapter caddyfile
ExecReload=$CADDY_BIN reload --config $CADDYFILE --adapter caddyfile --force
TimeoutStopSec=5s
LimitNOFILE=1048576
Restart=on-failure
RestartSec=5s
RuntimeDirectory=caddy
RuntimeDirectoryMode=0750
PrivateTmp=true
PrivateDevices=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/caddy /var/log/caddy
NoNewPrivileges=true
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --quiet "$UNIT_HOSTNAME" "$UNIT_CADDY"
}

render_step () {  # [--boot]: called from the hostname unit, which Caddy is ordered after: never wait on a Caddy job
  [ -s "$ETC_DIR/hostname" ] || die "no $ETC_DIR/hostname yet (run refresh-hostname.sh)"
  [ -s "$ETC_DIR/owner.bcrypt" ] || die "no $ETC_DIR/owner.bcrypt yet (run set-password.sh)"
  local host hash new="$CADDYFILE.new"
  host=$(head -1 "$ETC_DIR/hostname"); hash=$(head -1 "$ETC_DIR/owner.bcrypt")
  local galaxy=0; [ -f "${GALAXY_SITE_FLAG:-/nonexistent}" ] && galaxy=1
  print_caddyfile "$host" "$hash" "$galaxy" > "$new"
  chown root:caddy "$new"; chmod 0640 "$new"
  local out; out=$(as_caddy validate --config "$new" --adapter caddyfile 2>&1) \
    || { rm -f "$new"; die "caddy validate failed: $out"; }
  mv -f "$new" "$CADDYFILE"
  say "Caddyfile for https://$host/$([ "$galaxy" = 1 ] && echo " and https://galaxy.$host/")"
  if [ "${1:-}" = --boot ]; then
    # A blocking reload here would deadlock: the reload job waits for this unit's start job (Before=$UNIT_CADDY).
    if systemctl is-active --quiet "$UNIT_CADDY"; then systemctl --no-block reload "$UNIT_CADDY"; fi
  elif systemctl is-active --quiet "$UNIT_CADDY"; then systemctl reload "$UNIT_CADDY"
  else systemctl start "$UNIT_CADDY"
  fi
}

services_step () {
  say "replica services: $UNIT_API, $UNIT_WORKER, $UNIT_AUTOSCRIM + $TIMER_AUTOSCRIM (the timer stays disabled)"
  id -u "$REPLICA_USER" >/dev/null 2>&1 || die "run the user step first"
  [ -f "/etc/systemd/system/$UNIT_EGRESS" ] || die "run the egress step first"
  install -d -o root -g root -m 0755 "$ETC_DIR"
  if [ ! -s "$REPLICA_ENV" ]; then
    print_env > "$REPLICA_ENV.new"; chmod 0644 "$REPLICA_ENV.new"; mv -f "$REPLICA_ENV.new" "$REPLICA_ENV"
  else echo "keeping $REPLICA_ENV"; fi
  local name
  for name in "$UNIT_API" "$UNIT_WORKER" "$UNIT_AUTOSCRIM" "$TIMER_AUTOSCRIM"; do
    print_units | awk -v u="### $name" '$0 == u {on = 1; next} /^### / {on = 0} on' > "/etc/systemd/system/$name.new"
    [ -s "/etc/systemd/system/$name.new" ] || die "no unit text for $name"
    mv -f "/etc/systemd/system/$name.new" "/etc/systemd/system/$name"
  done
  print_cli > "$REPLICA_CLI.new"; chmod 0755 "$REPLICA_CLI.new"; mv -f "$REPLICA_CLI.new" "$REPLICA_CLI"
  systemctl daemon-reload
  systemctl enable --quiet "$UNIT_API" "$UNIT_WORKER"
  local repo; repo=$(sed -n 's/^REPLICA_REPO=//p' "$REPLICA_ENV" | tail -1)
  if [ ! -f "$repo/tools/replica/web.py" ]; then
    echo "!! $repo/tools/replica/web.py is missing: sync the replica code, then start $UNIT_API and $UNIT_WORKER"
    return 0
  fi
  systemctl restart "$UNIT_API"   # cheap; loads new code
  if systemctl is-active --quiet "$UNIT_WORKER"; then
    echo "kept $UNIT_WORKER running (restart it to load new code; running matches are requeued, no failure counted)"
  else systemctl start "$UNIT_WORKER"; fi
}

password_step () {
  local pw=""; IFS= read -r pw || true
  [ "${#pw}" -ge 16 ] || die "password on stdin is missing or shorter than 16 characters"
  [[ $pw =~ ^[A-Za-z0-9]+$ ]] || die "password must be alphanumeric"
  [ -x "$CADDY_BIN" ] || die "run the caddy step first"
  local hash; hash=$(printf '%s\n' "$pw" | as_caddy hash-password 2>/dev/null | tail -1)
  [[ $hash =~ $HASH_RE ]] || die "caddy hash-password returned no bcrypt hash"
  install -d -o root -g root -m 0755 "$ETC_DIR"
  (umask 077; printf '%s\n' "$hash" > "$ETC_DIR/owner.bcrypt.new")
  mv -f "$ETC_DIR/owner.bcrypt.new" "$ETC_DIR/owner.bcrypt"
  say "password hash updated"
  if [ -s "$ETC_DIR/hostname" ]; then render_step; else echo "(no host name yet: run refresh-hostname.sh)"; fi
}

status_step () {
  local u
  for u in "$UNIT_EGRESS" "$UNIT_HOSTNAME" "$UNIT_CADDY" "$UNIT_API" "$UNIT_WORKER" "$TIMER_AUTOSCRIM"; do
    printf '%-32s enabled=%-9s active=%s\n' "$u" "$(systemctl is-enabled "$u" 2>/dev/null || true)" "$(systemctl is-active "$u" 2>/dev/null || true)"
  done
  id "$REPLICA_USER" 2>/dev/null || echo "no user $REPLICA_USER"
  [ -s "$ETC_DIR/hostname" ] && echo "url: https://$(head -1 "$ETC_DIR/hostname")/"
  command -v nft >/dev/null && nft list table inet "$NFT_TABLE" 2>/dev/null || echo "no table inet $NFT_TABLE"
  local f
  for f in "$NFT_DROPIN" "$DBUS_POLICY"; do [ -f "$f" ] && echo "present: $f" || echo "MISSING: $f"; done
  echo "$UNIT_WORKER PrivateNetwork=$(systemctl show -p PrivateNetwork --value "$UNIT_WORKER" 2>/dev/null)"
  ss -ltnp | awk 'NR == 1 || /caddy|:'"$REPLICA_PORT"' /'
}

teardown_web () {
  say "teardown: Caddy"
  systemctl disable --now "$UNIT_CADDY" "$UNIT_HOSTNAME" 2>/dev/null || true
  rm -f "/etc/systemd/system/$UNIT_CADDY" "/etc/systemd/system/$UNIT_HOSTNAME"
  systemctl daemon-reload
  rm -rf /etc/caddy /var/lib/caddy /var/log/caddy "$CADDY_BIN" "$ETC_DIR/hostname" "$ETC_DIR/owner.bcrypt"
  id -u caddy >/dev/null 2>&1 && userdel caddy
  getent group caddy >/dev/null && groupdel caddy
  true
}

teardown_services () {
  say "teardown: replica services"
  systemctl disable --now "$TIMER_AUTOSCRIM" "$UNIT_AUTOSCRIM" "$UNIT_WORKER" "$UNIT_API" 2>/dev/null || true
  rm -f "/etc/systemd/system/$TIMER_AUTOSCRIM" "/etc/systemd/system/$UNIT_AUTOSCRIM" \
    "/etc/systemd/system/$UNIT_WORKER" "/etc/systemd/system/$UNIT_API" "$REPLICA_CLI"
  systemctl daemon-reload
}

teardown_all () {  # [--purge-data]
  teardown_web
  teardown_services
  if pgrep -u "$REPLICA_USER" >/dev/null 2>&1; then
    die "processes still run as $REPLICA_USER; stop the replica services first (lockdown kept)"
  fi
  say "teardown: egress lockdown, user $REPLICA_USER"
  systemctl disable --now "$UNIT_EGRESS" 2>/dev/null || true
  command -v nft >/dev/null && nft delete table inet "$NFT_TABLE" 2>/dev/null || true
  rm -f "/etc/systemd/system/$UNIT_EGRESS" "/etc/systemd/system/$SLICE" "$NFT_DROPIN" "$DBUS_POLICY"
  rmdir "$(dirname "$NFT_DROPIN")" 2>/dev/null || true
  systemctl is-active --quiet dbus.service && busctl call org.freedesktop.DBus /org/freedesktop/DBus \
    org.freedesktop.DBus ReloadConfig >/dev/null 2>&1 || true
  systemctl daemon-reload
  rm -rf "$ETC_DIR"
  id -nG "$OPERATOR_USER" | tr ' ' '\n' | grep -qx "$REPLICA_GROUP" && gpasswd -d "$OPERATOR_USER" "$REPLICA_GROUP" >/dev/null
  if id -u "$REPLICA_USER" >/dev/null 2>&1; then
    if [ "${1:-}" = --purge-data ]; then userdel -r "$REPLICA_USER" 2>/dev/null || userdel "$REPLICA_USER"; rm -rf "/home/$REPLICA_USER"
    else userdel "$REPLICA_USER"; echo "kept /home/$REPLICA_USER (owned by a deleted uid; --purge-data removes it)"; fi
  fi
  getent group "$REPLICA_GROUP" >/dev/null && groupdel "$REPLICA_GROUP"
  rm -rf "$LIB_DIR"
  true
}

step="${1:-}"; shift || true
case "$step" in
  all) install_step; user_step; egress_step; caddy_step; services_step ;;
  install) install_step ;;
  user) user_step ;;
  egress) egress_step ;;
  caddy) caddy_step ;;
  services) services_step ;;
  password) password_step ;;
  render) render_step "${1:-}" ;;
  status) status_step ;;
  teardown-web) teardown_web ;;
  teardown-services) teardown_services ;;
  teardown-all) teardown_all "${1:-}" ;;
  *) sed -n '2,/^set -e/{/^#/p}' "$0" >&2; exit 2 ;;
esac
